server:
  port: 8762

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/micro
      username: root
      password: root
      dbcp:
        validation-query: SELECT 1
        test-while-idle: true

  application:
      name: microservice-provider-user
  jpa:
      database: MYSQL
      show-sql: true
      #Hibernate ddl auto
      hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


